# Generated by Django 3.0 on 2022-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='image',
            field=models.ImageField(null=True, upload_to='example-images/%Y/%m/%d/'),
        ),
    ]
