# Generated by Django 3.0 on 2022-07-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
    ]
